#!/bin/bash
# Phase 7: Enum Synchronization Check Script
# Auto-generated by test_enum_sync.py

set -e

echo " Checking AttackStrategyType enum synchronization..."

# Extract backend enum values
echo " Extracting backend enum values..."
grep -A 100 "class AttackStrategyType" backend/core/models.py | \
  grep '= "' | awk -F'"' '{print $2}' | sort > /tmp/backend_strategies.txt

# Extract frontend enum values
echo " Extracting frontend enum values..."
grep -A 100 "export enum AttackStrategyType" frontend/src/types/api.ts | \
  grep '= "' | awk -F'"' '{print $2}' | sort > /tmp/frontend_strategies.txt

# Compare
echo "  Comparing enums..."
if diff /tmp/backend_strategies.txt /tmp/frontend_strategies.txt > /dev/null; then
    BACKEND_COUNT=$(wc -l < /tmp/backend_strategies.txt)
    echo " Enums synchronized: $BACKEND_COUNT strategies match"
    exit 0
else
    echo " Enum mismatch detected:"
    echo ""
    echo "Differences:"
    diff /tmp/backend_strategies.txt /tmp/frontend_strategies.txt || true
    echo ""
    echo "Backend count: $(wc -l < /tmp/backend_strategies.txt)"
    echo "Frontend count: $(wc -l < /tmp/frontend_strategies.txt)"
    exit 1
fi
